# Generated by Django 5.2.3 on 2025-06-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeSToreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(),
        ),
    ]
